version: "3.8"
services:
  backend:
    build: ./hollar-server
    ports: "3000:3000"
    env_file:
      - ./env
  frontend:
    build:
      context: ./hollar-client
      dockerfile: Dockerfile.dev
    ports: "5173:5173"
    stdin_open: true
    tty: true
    depends_on:
      - backend
